name: Build Docker Image
on: [workflow_dispatch]
jobs:
  build:
    runs-on: centos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Pull Docker Image with Digest
        run: |
          # 拉取指定 Tag 和 Digest 的镜像
          docker pull starrocks/artifacts-centos7:3.4.1@sha256:8bfaf7b93e54264d5669d98845034c171e5ac5c4856cd6d097144062c74d2ae3
          # 验证 Digest 是否匹配
          docker inspect --format='{{index .RepoDigests 0}}' starrocks/artifacts-centos7:3.4.1

      - name: Save Docker Image
        run: |
          docker save -o artifacts-centos7-3.4.1.tar starrocks/artifacts-centos7:3.4.1

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: starrocks-centos7-image
          path: artifacts-centos7-3.4.1.tar
